-- MySQL Script generated by MySQL Workbench
-- Tue Jan 17 19:09:16 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_resilia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_resilia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_resilia` DEFAULT CHARACTER SET utf8 ;
USE `db_resilia` ;

-- -----------------------------------------------------
-- Table `db_resilia`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_resilia`.`curso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_curso` VARCHAR(45) NOT NULL,
  `carga_horaria` INT NOT NULL,
  `valor` DECIMAL NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_resilia`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_resilia`.`professor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_professor` VARCHAR(45) NOT NULL,
  `endereco_professor` VARCHAR(45) NOT NULL,
  `telefone_professor` INT NOT NULL,
  `status_professor` VARCHAR(45) NOT NULL,
  `email_professor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_resilia`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_resilia`.`turma` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_inicio` DATE NOT NULL,
  `data_termino` DATE NOT NULL,
  `curso_id` INT NOT NULL,
  `professor_id` INT NOT NULL,
  PRIMARY KEY (`id`, `curso_id`, `professor_id`),
  INDEX `fk_turma_curso_idx` (`curso_id` ASC) VISIBLE,
  INDEX `fk_turma_professor1_idx` (`professor_id` ASC) VISIBLE,
  CONSTRAINT `fk_turma_curso`
    FOREIGN KEY (`curso_id`)
    REFERENCES `db_resilia`.`curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_professor1`
    FOREIGN KEY (`professor_id`)
    REFERENCES `db_resilia`.`professor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_resilia`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_resilia`.`aluno` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_aluno` VARCHAR(45) NOT NULL,
  `endereco_aluno` VARCHAR(45) NOT NULL,
  `telefone_aluno` INT NOT NULL,
  `status_aluno` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_resilia`.`matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_resilia`.`matricula` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_matricula` DATE NOT NULL,
  `aluno_id` INT NOT NULL,
  `turma_id` INT NOT NULL,
  PRIMARY KEY (`id`, `aluno_id`, `turma_id`),
  INDEX `fk_matricula_aluno1_idx` (`aluno_id` ASC) VISIBLE,
  INDEX `fk_matricula_turma1_idx` (`turma_id` ASC) VISIBLE,
  CONSTRAINT `fk_matricula_aluno1`
    FOREIGN KEY (`aluno_id`)
    REFERENCES `db_resilia`.`aluno` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matricula_turma1`
    FOREIGN KEY (`turma_id`)
    REFERENCES `db_resilia`.`turma` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
